### ISSUE TITLE
Replace Manual Cache With `setup-python` Cache

### ISSUE THREAD

**Issue by Behemyth** [sibyl-dev/pyreal#200]
### Description

A recent update to the `setup-python` action reduces the configuration required to setup dependency caching, an optimization for faster Action runs. The manual cache usage should be replaced with the auto-configured cache.

Note: pipx uses pip internally and only allows the installation of CLI applications. Poetry suggests its usage. It is pre-installed on all github-hosted runners.

See the [Action page](https://github.com/actions/setup-python) for examples.

```
steps:
- uses: actions/checkout@v3
- name: Install poetry
  run: pipx install poetry
- uses: actions/setup-python@v3
  with:
    python-version: '3.9'
    cache: 'poetry'
- run: poetry install
- run: poetry run pytest
```
